#spring.datasource.url=jdbc:mysql://apipl-db.clc9wkbwagzw.ap-northeast-2.rds.amazonaws.com:3306/oapdb
#spring.datasource.username=admin
#spring.datasource.password=dbfrhrfh1rk!
#spring.datasource.url=jdbc:mysql://192.168.1.254:3306/oapdb?useSSL=false

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=dbfrhrfh1rk!

#spring.security.user.name=user
#spring.security.user.password=password

spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/?serverTimezone=UTC
  username: root
  password: dbfrhrfh1rk!

 redis:
   port: 6379
   host: 127.0.0.1
   password: dbfrhrfh1rk!
   lettuce:
     pool:
       max-idle: 10
       min-idle: 2 
       max-active: 10
 
# security.user:
#   name: user
#   password: password
# thymeleaf:
#  prefix: classpath:/templates/
#  enabled: true
#  suffix: .html
#  check-template: true
#  check-template-location: true
#  mode: HTML
#  cache: false
 